/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.manager;

import Controller.ThongKeLinhKienDichVu;
import DAO.ThongKeLinhKienDichVuDAO;
import Model.NhanVien;
import View.user.GiaoDienChinhNVQuanLy;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;

/**
 *
 * @author dinhs
 */
public class GiaoDienThongKeLinhKienDichVuTheoDoanhThu extends javax.swing.JFrame {
    private NhanVien nv;
    private ArrayList<ThongKeLinhKienDichVu> ds = new ArrayList<>();
    DefaultTableModel dtmthongke;
    /**
     * Creates new form GiaoDienThongKeLinhKienDichVuTheoDoanhThu
     */
    public GiaoDienThongKeLinhKienDichVuTheoDoanhThu(NhanVien nv) {
        this.nv= nv;
        initComponents();
        jlbNhanVien.setText("Tài khoản của: "+nv.getTen());
    }

    public GiaoDienThongKeLinhKienDichVuTheoDoanhThu() {
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbThongKeLinhKienDichVu = new javax.swing.JTable();
        jlbNhanVien = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JButton();
        jdccKetThuc = new com.toedter.calendar.JDateChooser();
        jdcBatDau = new com.toedter.calendar.JDateChooser();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jtbThongKeLinhKienDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Linh kiên/ Dịch vụ", "Số lượng cung cấp", "Doanh thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbThongKeLinhKienDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbThongKeLinhKienDichVuMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtbThongKeLinhKienDichVuMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtbThongKeLinhKienDichVu);

        jlbNhanVien.setText("Tài khoản của:   ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Thống kê linh kiện dịch vụ theo doanh thu");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Ngày bắt đầu ");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Ngày kết thúc");

        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        jdccKetThuc.setDateFormatString("dd/MM/yyyy");

        jdcBatDau.setDateFormatString("dd/MM/yyyy");

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThongKe)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jdcBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdccKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuayLai)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbNhanVien)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuayLai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jdccKetThuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jdcBatDau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(btnThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        Date s = new Date();
        Date f = new Date();
        s = jdcBatDau.getDate();
        f = jdccKetThuc.getDate();
        if(s==null||f==null){
            JOptionPane.showMessageDialog(this, "chon khoang thoi gian thong ke");
            return;
        }
        if(s.compareTo(f)>0){
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phai trước ngày kết thúc");
            return;
        }
        ThongKeLinhKienDichVuDAO tkd = new ThongKeLinhKienDichVuDAO();
        ds=tkd.thongKeLinhKienDichVu(s, f);
        dtmthongke = (DefaultTableModel) jtbThongKeLinhKienDichVu.getModel();
        dtmthongke.setRowCount(0);
        for(ThongKeLinhKienDichVu x : ds){
            dtmthongke.addRow(new Object[] {x.getId(), x.getTen(), x.getSoLuong(), x.getDoanhThu()});
        }
        
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void jtbThongKeLinhKienDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbThongKeLinhKienDichVuMouseClicked
        // TODO add your handling code here:
        Date s = jdcBatDau.getDate();
        Date f = jdccKetThuc.getDate();
        int row = jtbThongKeLinhKienDichVu.getSelectedRow();
        String id = jtbThongKeLinhKienDichVu.getValueAt(row, 0).toString();
        if(evt.getClickCount()==2){
            GiaoDienChiTietThongKe view = new GiaoDienChiTietThongKe(id,nv, s, f);
            view.setLocationRelativeTo(null);
            view.setVisible(true);
        }
    }//GEN-LAST:event_jtbThongKeLinhKienDichVuMouseClicked

    private void jtbThongKeLinhKienDichVuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbThongKeLinhKienDichVuMouseReleased
        // TODO add your handling code here:
        if(jtbThongKeLinhKienDichVu.isEditing()){
            int row = jtbThongKeLinhKienDichVu.getSelectedRow();
            int colum = jtbThongKeLinhKienDichVu.getSelectedColumn();
            jtbThongKeLinhKienDichVu.getCellEditor(row,colum).cancelCellEditing();
        }
    }//GEN-LAST:event_jtbThongKeLinhKienDichVuMouseReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here
    }//GEN-LAST:event_formWindowClosed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        GiaoDienXemThongKe win = new GiaoDienXemThongKe(nv);
        win.setLocationRelativeTo(null);
        win.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongKeLinhKienDichVuTheoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongKeLinhKienDichVuTheoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongKeLinhKienDichVuTheoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienThongKeLinhKienDichVuTheoDoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienThongKeLinhKienDichVuTheoDoanhThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcBatDau;
    private com.toedter.calendar.JDateChooser jdccKetThuc;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JTable jtbThongKeLinhKienDichVu;
    // End of variables declaration//GEN-END:variables
}
